workflows:
  ios-workflow:
    name: Job Zinda iOS
    max_build_duration: 120

    environment:
      flutter: stable

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jobZinda.custom

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Set up iOS code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log