// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqnUJIiSkDLzThCxDiQLU2GW-5VOLVMio',
    appId: '1:339130305640:web:f114e0e832c151c9dfbfdd',
    messagingSenderId: '339130305640',
    projectId: 'bizire-35301',
    authDomain: 'bizire-35301.firebaseapp.com',
    storageBucket: 'bizire-35301.appspot.com',
    measurementId: 'G-DNVBQTD7Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2ehzEZN6ORFA9SHlhYOdr8ipsrUuXPg',
    appId: '1:210810815563:android:bd982b181396b9e2d7f9ce',
    messagingSenderId: '210810815563',
    projectId: 'transbus-f69a6',
    storageBucket: 'transbus-f69a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvob-hI2AQCM568tRQFu3Jo5VuXSpxWYg',
    appId: '1:339130305640:ios:1163387bea848849dfbfdd',
    messagingSenderId: '339130305640',
    projectId: 'bizire-35301',
    storageBucket: 'bizire-35301.appspot.com',
    iosBundleId: 'com.triliaonlineschool.pFlutterSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvob-hI2AQCM568tRQFu3Jo5VuXSpxWYg',
    appId: '1:339130305640:ios:f9dcf7ff526f4613dfbfdd',
    messagingSenderId: '339130305640',
    projectId: 'bizire-35301',
    storageBucket: 'bizire-35301.appspot.com',
    iosBundleId: 'com.triliaonlineschool.pFlutterSetup.RunnerTests',
  );
}
